create database if not exists concesionario;

show databases;

use concesionario;

-- MySQL Script generated by MySQL Workbench
-- Wed Jun  8 07:58:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concesionario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concesionario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concesionario` DEFAULT CHARACTER SET utf8 ;
USE `concesionario` ;

-- -----------------------------------------------------
-- Table `concesionario`.`coches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`coches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

ALTER TABLE `concesionario`.`grupo` 
CHANGE COLUMN `id` `id` INT NOT NULL AUTO_INCREMENT ;

-- -----------------------------------------------------
-- Table `mydb`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`vendedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `sueldo` FLOAT NOT NULL,
  `comision` FLOAT NOT NULL,
  `jefe` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `grupo_id_idx` (`grupo_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `grupo_id`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `concesionario`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vendedor_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `gastado` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `vendedor_id_idx` (`vendedor_id` ASC) VISIBLE,
  CONSTRAINT `vendedor_id`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `concesionario`.`vendedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concesionario`.`encargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `coche_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `coche_id_idx` (`coche_id` ASC) VISIBLE,
  INDEX `cliente_id_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `coche_id`
    FOREIGN KEY (`coche_id`)
    REFERENCES `concesionario`.`coches` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `concesionario`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------------------
-- rellenando las tablas con datos
-- ----------------------------------------------------------------

-- ----------------------------------------------------------
-- rellenando tabla de coches
-- ----------------------------------------------------------

insert into coches(modelo,marca,precio,stock) values
('renault clio','renault',12000,13),
('seat panda','seat',10000,10),
('mercedes ranchera','mercedes benz',32000,24),
('porche cayene','porche',65000,5),
('lambo aventador','lamborgini',170000,2),
('ferrari spider','ferrari',24500,80);

select * from coches;

-- ----------------------------------------------------------
-- rellenando tabla de grupos
-- ----------------------------------------------------------

insert into grupo(nombre,ciudad) values
('vendedores a','madrid'),
('vendedores b','madrid'),
('directores mecanicos','madrid'),
('vendedores a','barcelona'),
('vendedores b','barcelona'),
('vendedores c','valencia'),
('vendedores a','bilbao'),
('vendedores b','pamplona'),
('vendedores c','santiago')
;

select * from grupo;

-- ----------------------------------------------------------
-- rellenando tabla de vendedores
-- ----------------------------------------------------------

insert into vendedores(grupo_id,nombre,apellido,cargo,fecha_alta,sueldo,comision,jefe) values 
(1,'david','lopez','responsable de tienda',current_date(),30000,4,null),
(1,'fran','martinez','ayudante de tienda',current_date(),23000,2,1),
(2,'nelson','sanchez','responsable de tienda',current_date(),38000,4,null),
(2,'jesus','lopez','ayudante de tienda',current_date(),12000,6,3),
(3,'victor','lopez','mecanico jefe',current_date(),50000,2,null),
(4,'antonio','lopez','vendedor de recambios',current_date(),13000,4,null),
(5,'salvador','lopez','vendedor eperto',current_date(),60000,2,null),
(6,'joaquin','lopez','ejecutivo de cuentas',current_date(),80000,4,null),
(6,'luis','lopez','ayudante de tienda',current_date(),10000,10,8)
;

select * from vendedores;

-- ----------------------------------------------------------
-- rellenando tabla de clientes
-- ----------------------------------------------------------

insert into clientes(vendedor_id,nombre,ciudad,gastado,fecha) values 
(1,'construcciones diaz inc','alcovendas',24000,current_date()),
(1,'fruteria antonia','fuenlabrada',40000,current_date()),
(1,'imprenta martinez barcelona','alcovendas',32000,current_date()),
(1,'jesus colchones prat','alcovendas',96000,current_date()),
(1,'bar pepe inc','valencia',170000,current_date()),
(1,'tiend PC inc','murcia',245000,current_date())
;

select * from clientes;
-- ----------------------------------------------------------
-- rellenando tabla de encargos
-- ----------------------------------------------------------

insert into encargos(coche_id,cliente_id,cantidad,fecha) values
(1,1,2,current_date()),
(2,2,4,current_date()),
(3,3,1,current_date()),
(4,3,3,current_date()),
(5,5,1,current_date()),
(6,6,1,current_date())
;

select * from encargos;

-- -----------------------------------------------


-- @@@@@ coches que ha comprado cada cliente y su modelo

select cantidad, nombre from encargos e, clientes c where e.cliente_id = c.id;

select cantidad, nombre, modelo from encargos e 
inner join clientes c on e.cliente_id = c.id
inner join coches co on e.coche_id = co.id;





